kind: pipeline
name: default

clone:
  depth: 5

steps:
- name: build go
  image: golang:1.11
  commands:
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -tags netgo -o release/linux/amd64/drone-git-with-ssh

- name: build docker image (dry_run)
  image: plugins/docker
  settings:
    username: matsubara0507
    password:
      from_secret: docker_hub_password
    repo: matsubara0507/git-with-ssh
    dry-run: true
  when:
    event:
      exclude:
        - pull_request
