kind: pipeline
name: default

clone:
  depth: 5

steps:
- name: build go
  image: golang:1.11
  commands:
  - go build
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -tags netgo -o release/linux/amd64/drone-git-with-ssh

- name: test
  image: golang:1.11
  environment:
    SSH_KEY: 'aaa\nbbb'
  commands:
  - printf $SSH_KEY > ./test/expected/.ssh/id_rsa && chmod 600 ./test/expected/.ssh/id_rsa
  - ./drone-git-with-ssh --home ./test/result --ssh-private-key $SSH_KEY --hosts github.com --hosts bitbucket.org
  - diff ./test/result/.ssh ./test/expected/.ssh

- name: build docker image (dry_run)
  image: plugins/docker
  settings:
    username: matsubara0507
    password:
      from_secret: docker_hub_password
    repo: matsubara0507/git-with-ssh
    dry-run: true
  when:
    event:
      exclude:
        - pull_request

- name: push docker image
  image: plugins/docker
  settings:
    username: matsubara0507
    password:
      from_secret: docker_hub_password
    repo: matsubara0507/git-with-ssh
  when:
    branch:
    - master
    event:
      exclude:
        - pull_request
